<?php
    $_categories = $block->getCategories();
    if (!count($_categories)) {
        return;
    }

    $columnsCount = $block->getColumnCount();
    $linkAsButton = $block->getLinkAsButton();
    $height = $block->getImageHeight();
    $width = $block->getImageWidth();
    $maxCategoryCount = $block->getCategoryCount();
    $maxSubcategoryCount = $block->getSubcategoryCount();
    $i = 0;
?>

<div class="easycatalogimg">
<ul class="easycatalogimg-listing easycatalogimg-<?php echo $block->getMode() ?> easycatalogimg-cols-<?php echo $columnsCount ?>">
<?php foreach ($_categories as $_category) : ?>

    <?php if ($i++ >= $maxCategoryCount): break; endif; ?>

    <li class="item">
        <?php if ($block->getParentCategoryPosition() === 'top') : ?>
            <?php if ($linkAsButton): ?>
                <div class="category-name parent-category">
                    <h2 class="name"><?php echo $block->escapeHtml($_category->getName()) ?></h2>
                    <div class="category-link"><a class="action primary" href="<?php echo $this->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><span><?= __('Shop Now') ?></span></a></div>
                </div>
            <?php else: ?>
                <div class="category-name parent-category parent-category-top"><a href="<?php echo $this->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a></div>
            <?php endif ?>
        <?php endif ?>

        <?php if ($block->getShowImage()) : ?>
            <?php
                $style = '';
                if (!empty($width)) {
                    $style = 'width: ' . (is_numeric($width) ? $width . 'px' : $width);
                } else if (!empty($height)) {
                    $style = 'height: ' . (is_numeric($height) ? $height . 'px' : $height);
                }
                $srcset = $this->getImageSrcset($_category, $width, $height);
            ?>

            <a href="<?php echo $this->getCategoryUrl($_category) ?>"
                title="<?php echo $block->escapeHtml($_category->getName()) ?>"
                class="image"
            ><img alt="<?php echo $block->escapeHtml($_category->getName()) ?>"
                src="<?php echo $this->getImageSrc($_category, $width, $height) ?>"
                <?php echo $srcset ? 'srcset="' . $srcset . '"' : '' ?>
                <?php echo $width  ? 'width="' . $width . '"' : '' ?>
                <?php echo $height ? 'height="' . $height . '"' : '' ?>
                <?php echo $style  ? 'style="' . $style . '"' : '' ?>
            /></a>
        <?php endif; ?>

        <?php if ($block->getParentCategoryPosition() !== 'top') : ?>
            <div class="category-name parent-category"><a href="<?php echo $this->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>"><?php echo $block->escapeHtml($_category->getName()) ?></a></div>
        <?php endif ?>

        <?php
        $_subcategories = $_category->getSubcategories();
        if ($maxSubcategoryCount && $_subcategories) :
            $j = 0;
            $_count = count($_subcategories);
            // display More link, if more than one subcategory is not shown, otherwise - display last category
            $_displayMoreLink = $_count > $maxSubcategoryCount + 1;
            if ($_count) : ?>
                <ul class="list-subcategories">
                <?php foreach ($_subcategories as $_subcategory) :
                    if ($_displayMoreLink && ($j > $maxSubcategoryCount - 1)): ?>
                        <li>
                            <a href="<?php echo $this->getCategoryUrl($_category) ?>" title="<?php echo $block->escapeHtml($_category->getName()) ?>" class="link-more"><?php echo __('More in %1...', $block->escapeHtml($_category->getName())); ?></a>
                        </li>
                        <?php break;
                    endif; ?>
                    <li>
                        <a href="<?php echo $this->getCategoryUrl($_subcategory) ?>"
                            title="<?php echo $block->escapeHtml($_subcategory->getName())?>"
                            class="category-name child-category"><?php
                            echo $block->escapeHtml($_subcategory->getName());
                        ?></a>
                    </li>
                    <?php $j++; ?>
                <?php endforeach;?>
                </ul>
            <?php
            endif;
        endif; ?>
    </li>

<?php endforeach; ?>
</ul>
</div>
